resources:
- name: gohello-git
  type: git
  icon: github
  source:
    uri: ((git-repo-uri))
    branch: main

- name: ((image-name))
  type: registry-image
  icon: docker
  source:
    ca_certs: ((certs))
    repository: ((image-repo-name))/library/((image-name))
    username: ((registry-username))
    password: ((registry-password))
    tag: ((tag-app))
    insecure: true

jobs:
- name: build-and-publish
  public: true
  serial: true
  plan:
  - get: gohello-git
    trigger: true
  - task: build-and-push-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          ca_certs: ((certs))
          # repository: concourse/oci-build-task
          repository: ((image-repo-name))/library/concourse/oci-build-task
          insecure: true
      inputs:
      - name: gohello-git
      outputs:
      - name: image
      params:
        CONTEXT: gohello-git/
      run:
        path: build
  - put: ((image-name))
    params:
      image: image/image.tar

- name: unit-test
  public: true
  plan:
  - get: gohello-git
    passed: [build-and-publish]
    trigger: false
  - task: run-unit-test
    config:
      inputs:
        - name: gohello-git
      platform: linux
      image_resource:
        type: registry-image
        # source: { repository: bitnami/kubectl }
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          ca_certs: ((certs))
          repository: harbor.test.harbor.local/library/helm
          # repository: ((image-repo-name))/library/concourse/oci-build-task
          insecure: true
      run:
        path: /bin/sh
        args:
          - "-e"
          - "-c"
          - |
            echo "Run fake unit test (sleep 15s) : $(date '+%Y-%m-%d %H:%M:S')"
            sleep 15s

- name: deploy-gohelloapp
  public: true
  plan:
  - get: gohello-git
    passed: [unit-test]
    trigger: false
  - task: helm-deploy-kube-app
    config:
      inputs:
        - name: gohello-git
      platform: linux
      image_resource:
        type: registry-image
        # source: { repository: bitnami/kubectl }
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          ca_certs: ((certs))
          repository: harbor.test.harbor.local/library/helm
          # repository: ((image-repo-name))/library/concourse/oci-build-task
          insecure: true
      run:
        path: /bin/sh
        args:
          - "-e"
          - "-c"
          - |
            echo "current date is: $(date '+%Y-%m-%d %H:%M:S')"
            ls -la ./
            mkdir -p ~/.kube
            echo ((kube)) | base64 -di > ~/.kube/config
            helm upgrade --create-namespace --install ((image-name)) gohello-git/gohelloapp --namespace ((image-name)) -f gohello-git/values.yaml --set replicaCount=((rplcount)) --dry-run
            helm upgrade --create-namespace --install ((image-name)) gohello-git/gohelloapp  --namespace ((image-name)) -f gohello-git/values.yaml --set replicaCount=((rplcount))

 
