resources:
- name: gohello-git
  type: git
  icon: github
  source:
    uri: ((git-repo-uri))
    branch: main

- name: ((image-name))
  type: registry-image
  icon: docker
  source:
    ca_certs: ((certs))
    repository: ((image-repo-name))/library/((image-name))
    username: ((registry-username))
    password: ((registry-password))
    tag: ((tag-app))
    insecure: true

jobs:
- name: build-and-publish-((image-name))
  public: true
  plan:
  - get: gohello-git
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          ca_certs: ((certs))
          repository: concourse/oci-build-task
          # repository: ((image-repo-name))/library/concourse/oci-build-task
          insecure: true
      inputs:
      - name: gohello-git
      outputs:
      - name: image
      params:
        CONTEXT: gohello-git/
        # UNPACK_ROOTFS: "true" # only needed if using image in a future step
      run:
        path: build
  - put: ((image-name))
    params:
      image: image/image.tar
      # tag: latest

  - task: kubedeploy
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: bitnami/kubectl }
      run:
        path: /bin/sh
        args:
          - "-e"
          - "-c"
          - |
            echo "current date is: $(date '+%Y-%m-%d %H:%M:S')"
            pwd ; id ; ls -l ./
# jobs:
# - name: job
#   public: true
#   plan:
#   - get: gohello-git
#     trigger: true
#   - task: list-files
#     config:
#       inputs:
#         - name: gohello-git
#       platform: linux
#       image_resource:
#         type: registry-image
#         source: { repository: busybox }
#       run:
#         path: /bin/ash
#         args:
#           - "-e"
#           - "-c"
#           - |
#             echo "current date is: $(date '+%Y-%m-%d %H:%M:S')"
#             ls -l ./gohello-git



