resources:
- name: gohello-git
  type: git
  icon: github
  source:
    uri: ((git-repo-uri))
    branch: main

- name: ((image-name))
  type: registry-image
  icon: docker
  source:
    ca_certs: ((certs))
    repository: ((image-repo-name))/library/((image-name))
    username: ((registry-username))
    password: ((registry-password))
    tag: ((tag-app))
    insecure: true

jobs:
- name: build-and-publish-gohello
  public: true
  plan:
  - get: gohello-git
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          ca_certs: ((certs))
          # repository: concourse/oci-build-task
          repository: ((image-repo-name))/library/concourse/oci-build-task
          insecure: true
      inputs:
      - name: gohello-git
      outputs:
      - name: image
      params:
        CONTEXT: gohello-git/
        # UNPACK_ROOTFS: "true" # only needed if using image in a future step
      run:
        path: build
  - put: ((image-name))
    params:
      image: image/image.tar
      # tag: latest

# - name: deploy-kube-gohello-app
#   public: true
#   plan:
#   - get: every-30s
#     passed: [build-and-publish-gohello]
#     trigger: true
  - task: deploy-kube-app
    config:
      inputs:
        - name: gohello-git
      platform: linux
      image_resource:
        type: registry-image
        # source: { repository: bitnami/kubectl }
        source:
          # Check out the README for oci-build-task at
          # https://github.com/concourse/oci-build-task
          ca_certs: ((certs))
          repository: harbor.test.harbor.local/library/kubectl
          # repository: ((image-repo-name))/library/concourse/oci-build-task
          insecure: true
      run:
        path: /bin/sh
        args:
          - "-e"
          - "-c"
          - |
            echo "current date is: $(date '+%Y-%m-%d %H:%M:S')"
            ls -la ./
            mkdir -p ~/.kube
            echo ((kube)) | base64 -di > ~/.kube/config
            helm upgrade --create-namespace --install gohelloapp gohelloapp --namespace gohelloapp -f gohello-git/values.yaml --set replicaCount=((rplcount)) --dry-run
            helm upgrade --create-namespace --install gohelloapp gohelloapp --namespace gohelloapp -f gohello-git/values.yaml --set replicaCount=((rplcount))

  # - task: deploy-kube-app
  #   config:
  #     inputs:
  #       - name: gohello-git
  #     platform: linux
  #     image_resource:
  #       type: registry-image
  #       # source: { repository: bitnami/kubectl }
  #       source:
  #         # Check out the README for oci-build-task at
  #         # https://github.com/concourse/oci-build-task
  #         ca_certs: ((certs))
  #         repository: harbor.test.harbor.local/library/kubectl
  #         # repository: ((image-repo-name))/library/concourse/oci-build-task
  #         insecure: true
  #     run:
  #       path: /bin/sh
  #       args:
  #         - "-e"
  #         - "-c"
  #         - |
  #           echo "current date is: $(date '+%Y-%m-%d %H:%M:S')"
  #           ls -la ./
  #           mkdir -p ~/.kube
  #           echo ((kube)) | base64 -di > ~/.kube/config
  #           kubectl apply -f gohello-git/deploy.yaml 
# jobs:
# - name: job
#   public: true
#   plan:
#   - get: gohello-git
#     trigger: true
#   - task: list-files
#     config:
#       inputs:
#         - name: gohello-git
#       platform: linux
#       image_resource:
#         type: registry-image
#         source: { repository: busybox }
#       run:
#         path: /bin/ash
#         args:
#           - "-e"
#           - "-c"
#           - |
#             echo "current date is: $(date '+%Y-%m-%d %H:%M:S')"
#             ls -l ./gohello-git



